[package]
name = "worldinfo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slab = "0.4"
bitstream-io = "1"
osrs-buffer = "0.5"